cargo-features = ["edition2024"]

[package]
name = "cli"
version = "0.1.0"
edition = "2024"

[dependencies]
vm = { path = "../vm" }
# parser = { path = "../parser" }
# assembler = { path = "../assembler" }
# repl = { path = "../repl" }

[[bin]]
name = "susuro"
path = "src/main.rs"
